Add test for element.props
The unit tests fail if the element has a attribute called type, since that
triggers it thinking it is a React Tree.  Adds an additional check for
element.props which is assumed exists causing the error below.

```
  1) full post content fixture core-gallery:
     TypeError: Cannot read property 'children' of undefined
      at normalizeReactTree (build/test.js:8785:20)
      at build/test.js:8770:11
      at Array.map (native)
      at normalizeReactTree (build/test.js:8769:18)
      at build/test.js:8804:26
      at Array.map (native)
      at normalizeParsedBlocks (build/test.js:8795:16)
      at Context.<anonymous> (build/test.js:8816:33)
```