fix: Patch react-devtools-core to support jsdom-jscore-rn (#47616)
* fix: Patch react-devtools-core to support jsdom-jscore-rn

The native editor defining `window.document` caused
`react-devtools-core` to believe the environment was a browser, not
React Native. This resulted in the following error when inspecting
components using the React Dev Tools:

Android:
```
Cannot set property 'zIndex' of undefined
```

iOS:
```
TypeError: undefined is not an object (evaluating
'this.container.style.zIndex = '10000000'')
```

* docs: Fix inline comment typo